import operator
from typing import Annotated, List, TypedDict

from langchain_core.messages import BaseMessage


class AgentState(TypedDict):
    messages: Annotated[List[BaseMessage], operator.add]

    next_node: str | None
    # "text_agent", "vision_agent", "web_agent", "sql_agent",
    # "grader", "query_rewriter", or "FINISH"

    retrieved_text: List[dict]
    retrieved_images: List[dict]
    thought_process: List[dict]
    # [{"agent": "...", "action": "..."}]

    # --- Self-RAG & Evaluation State Attributes ---

    retrieval_relevance_score: str | float | None
    # "yes"/"no" or numerical confidence (0.0 - 1.0)

    retry_count: int
    # Counter for re-search rewrite loops (default: 0)

    # --- Text-to-SQL State Attributes ---
    sql_query: str | None  # Raw SQL query generated by SQL Agent
    sql_result: List[dict] | str | None  # Direct SQL execution results from database
